# Generated by Django 5.0.1 on 2024-02-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tryit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField(default='')),
                ('aadhar', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
